### ISSUE TITLE
what is backend language for this course ?

### ISSUE THREAD

**Issue by PManager1** [StephenGrider/GraphQLCasts#3]

**Comment by PManager1** [comment]
dude, if i know graphQL, whats the suggested backend for the app , is it meteor or something else ?  whats easy and scalable ?

**Comment by annielmenezes** [comment]
@jpca999 this course use Javascript for both backend and frontend side, Meteor is a framework implemented in Javascript

**Comment by sagnikghoshcr7** [comment]
JS

**Comment by PManager1** [comment]
you fu kks woke up after five years ?
